// Golden puzzle fixtures for M0. Each `puzzle` is 81 chars ('0' = empty).
// These are well-known human-solvable puzzles used to validate solver/hint/analysis.
export type Golden = { id: string; puzzle: string; solution: string };

// A classic "easy" puzzle solvable with singles (naked/hidden single).
export const EASY: Golden = {
  id: "easy-1",
  puzzle:
    "530070000600195000098000060800060003400803001700020006060000280000419005000080079",
  solution:
    "534678912672195348198342567859761423426853791713924856961537284287419635345286179",
};

// A puzzle that genuinely requires locked candidates (pointing) beyond singles.
// Verified by analyze(): solves at L3 with maxRequiredTechnique="pointing-pair".
export const LOCKED: Golden = {
  id: "locked-1",
  puzzle:
    "400000938032094100095300240370609004529001673604703090957008300003900400240030709",
  solution:
    "461572938732894156895316247378629514529481673614753892957248361183967425246135789",
};

// ---------------------------------------------------------------------------
// Low-1 fix (Gate Review): golden puzzles that genuinely exercise the L3/L4
// techniques that previously had NO end-to-end positive coverage. Each `requires`
// entry lists a technique that MUST appear in solve(board, 4)'s step trace.
// These puzzles were generated by digging holes from a random full solution while
// keeping a unique solution (verified by checkUniqueness); solutions below are the
// exact unique solutions.
// ---------------------------------------------------------------------------
export type TechGolden = Golden & { requires: string[] };

// Trace techniques: hidden-single, naked-single, pointing-pair, box-line-reduction.
export const BOX_LINE: TechGolden = {
  id: "box-line-1",
  puzzle:
    "080050400000900600609074820000000000278000000000100263100000050030000007040000000",
  solution:
    "781256439423918675659374821316425798278693514594187263167849352832561947945732186",
  requires: ["box-line-reduction"],
};

// Trace techniques: hidden-single, naked-single, pointing-pair, naked-pair, hidden-pair.
export const NAKED_PAIR: TechGolden = {
  id: "naked-pair-1",
  puzzle:
    "000000900300020000081300450400800100037000000069407000000010000000900840000000312",
  solution:
    "574681923396524781281379456425863179837192564169457238743218695612935847958746312",
  requires: ["naked-pair", "hidden-pair"],
};

// Trace techniques: hidden-single, naked-single, pointing-pair, pointing-triple, hidden-pair.
export const POINTING_TRIPLE: TechGolden = {
  id: "pointing-triple-1",
  puzzle:
    "000086000906050000000000900001600300062500001005008400400000000080004203000090180",
  solution:
    "174986532936452718258731946841679325762543891395218467413827659589164273627395184",
  requires: ["pointing-triple", "hidden-pair"],
};

// Trace techniques: hidden-single, naked-single, pointing-pair, box-line-reduction, naked-triple.
export const NAKED_TRIPLE: TechGolden = {
  id: "naked-triple-1",
  puzzle:
    "050401000090000000300600000100000700000094050270000030008100900000903240000006310",
  solution:
    "752431896691258473384679521145362789863794152279815634438127965516983247927546318",
  requires: ["naked-triple", "box-line-reduction"],
};

// All technique-coverage fixtures, for iteration in tests.
export const TECH_GOLDENS: TechGolden[] = [BOX_LINE, NAKED_PAIR, POINTING_TRIPLE, NAKED_TRIPLE];

